pullRequestPreviewsEnabled: true

envVarGroups:
- name: yaml-pr-test-evg
  envVars:
  - key: evg-test-key-1
    value: env-test-value-1
- name: taml-pr-test-2
  envVars:
  - key: anotherVar
    value: anotherVal

services:
- type: web
  name: yaml-pr-test-node
  env: node
  buildCommand: yarn
  startCommand: node index.js && true
  envVars:
  - key: test
    value: tested
  - key: neededThis
    value: fakeval
  - key: DB_URL
    fromDatabase:
      name: another_db
      property: connectionString
  - key: REDIS_URL
    fromService:
      name: redis
      type: pserv
      property: hostport
# A private Redis instance
- type: pserv
  name: redis
  env: docker
  repo: https://github.com/render-examples/redis.git
  envVars:
  - key: GENERATED_SECRET
    generateValue: true
  - key: DASHBOARD_SECRET
    sync: false
  disk:
    name: redis-data
    mountPath: /var/lib/redis
    sizeGB: 10                # optional
  autoDeploy: false             # optional

databases:
- name: another_db
  databaseName: myotherdb
  user: myotheruser
  plan: Starter
